# Generated by Django 5.1 on 2024-09-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useravatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(default='media/media/UserAvatars/img.png', upload_to='media/UserAvatars', verbose_name='Аватар'),
        ),
    ]
