# Generated by Django 5.1 on 2024-09-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useravatar_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAvatar',
        ),
    ]
