# Generated by Django 5.1 on 2024-08-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_added', models.DateTimeField(auto_now=True, verbose_name='Дата добавления')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
