# Generated by Django 5.1 on 2024-09-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_orderphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderphotos',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/orderPhotos', verbose_name='Фото'),
        ),
    ]
