# Generated by Django 5.1 on 2024-09-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_orderphotos_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/orderPhotos', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='OrderPhotos',
        ),
    ]
